import type { Subject, Teacher, Course, Lecture } from "@/types";

export const SUBJECTS: Subject[] = [
  {
    id: "math",
    name: "الرياضيات",
    icon: "📐",
    color: "from-blue-500 to-blue-700",
    description: "جبر، هندسة، تفاضل وتكامل",
    courseCount: 8,
  },
  {
    id: "physics",
    name: "الفيزياء",
    icon: "⚛️",
    color: "from-purple-500 to-purple-700",
    description: "ميكانيكا، كهرباء، موجات",
    courseCount: 6,
  },
  {
    id: "chemistry",
    name: "الكيمياء",
    icon: "🧪",
    color: "from-green-500 to-green-700",
    description: "عضوية، غير عضوية، تحليلية",
    courseCount: 5,
  },
  {
    id: "biology",
    name: "الأحياء",
    icon: "🧬",
    color: "from-teal-500 to-teal-700",
    description: "خلية، وراثة، أحياء دقيقة",
    courseCount: 4,
  },
  {
    id: "arabic",
    name: "اللغة العربية",
    icon: "📖",
    color: "from-orange-500 to-orange-700",
    description: "نحو، صرف، أدب",
    courseCount: 7,
  },
  {
    id: "english",
    name: "اللغة الإنجليزية",
    icon: "🌐",
    color: "from-sky-500 to-sky-700",
    description: "grammar, vocabulary, reading",
    courseCount: 5,
  },
  {
    id: "history",
    name: "التاريخ",
    icon: "🏛️",
    color: "from-amber-500 to-amber-700",
    description: "تاريخ مصر، التاريخ العالمي",
    courseCount: 3,
  },
  {
    id: "geology",
    name: "الجيولوجيا",
    icon: "🌍",
    color: "from-stone-500 to-stone-700",
    description: "صخور، معادن، تضاريس",
    courseCount: 2,
  },
];

export const TEACHERS: Teacher[] = [
  {
    id: "t1",
    name: "أ. أحمد الشامي",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=Ahmed&backgroundColor=1a4fc4&textColor=ffffff",
    subjects: ["math"],
    bio: "خبرة 15 سنة في تدريس الرياضيات للثانوية",
    courseCount: 4,
  },
  {
    id: "t2",
    name: "أ. سارة محمد",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=Sara&backgroundColor=0ea5e9&textColor=ffffff",
    subjects: ["physics", "math"],
    bio: "دكتوراه فيزياء، خبرة 10 سنوات",
    courseCount: 3,
  },
  {
    id: "t3",
    name: "أ. كريم عبدالله",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=Karim&backgroundColor=10b981&textColor=ffffff",
    subjects: ["chemistry"],
    bio: "أستاذ كيمياء معتمد، مؤلف كتب تعليمية",
    courseCount: 3,
  },
  {
    id: "t4",
    name: "أ. منى إبراهيم",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=Mona&backgroundColor=f97316&textColor=ffffff",
    subjects: ["arabic"],
    bio: "ماجستير لغة عربية، خبرة 12 سنة",
    courseCount: 3,
  },
  {
    id: "t5",
    name: "أ. هشام الطيب",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=Hesham&backgroundColor=8b5cf6&textColor=ffffff",
    subjects: ["biology"],
    bio: "طبيب وأستاذ أحياء، خبرة 8 سنوات",
    courseCount: 2,
  },
];

export const COURSES: Course[] = [
  {
    id: "c1",
    title: "الرياضيات الثانوية – الصف الأول",
    subjectId: "math",
    teacherId: "t1",
    description: "كورس شامل في الجبر والهندسة للصف الأول الثانوي",
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&q=80",
    lectureCount: 24,
    level: "الصف الأول",
    isVisible: true,
    progress: 65,
  },
  {
    id: "c2",
    title: "التفاضل والتكامل – الصف الثالث",
    subjectId: "math",
    teacherId: "t1",
    description: "شرح مبسط للتفاضل والتكامل مع تطبيقات",
    thumbnail: "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=400&q=80",
    lectureCount: 18,
    level: "الصف الثالث",
    isVisible: true,
    progress: 30,
  },
  {
    id: "c3",
    title: "الفيزياء الحديثة – الصف الثالث",
    subjectId: "physics",
    teacherId: "t2",
    description: "الفيزياء النووية والكمومية بأسلوب مبسط",
    thumbnail: "https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=400&q=80",
    lectureCount: 16,
    level: "الصف الثالث",
    isVisible: true,
    progress: 0,
  },
  {
    id: "c4",
    title: "الكيمياء العضوية – الصف الثاني",
    subjectId: "chemistry",
    teacherId: "t3",
    description: "المركبات العضوية والتفاعلات الكيميائية",
    thumbnail: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&q=80",
    lectureCount: 20,
    level: "الصف الثاني",
    isVisible: true,
    progress: 80,
  },
  {
    id: "c5",
    title: "اللغة العربية – النحو والصرف",
    subjectId: "arabic",
    teacherId: "t4",
    description: "قواعد النحو والصرف بأسلوب سهل وممتع",
    thumbnail: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80",
    lectureCount: 15,
    level: "الصف الثاني",
    isVisible: true,
    progress: 45,
  },
  {
    id: "c6",
    title: "الأحياء – الوراثة والتطور",
    subjectId: "biology",
    teacherId: "t5",
    description: "علم الوراثة والجينات والتطور",
    thumbnail: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&q=80",
    lectureCount: 12,
    level: "الصف الثالث",
    isVisible: true,
    progress: 15,
  },
  {
    id: "c7",
    title: "الفيزياء – الكهرباء والمغناطيسية",
    subjectId: "physics",
    teacherId: "t2",
    description: "شرح تفصيلي للكهرباء والمغناطيس مع تمارين",
    thumbnail: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&q=80",
    lectureCount: 14,
    level: "الصف الثاني",
    isVisible: true,
    progress: 0,
  },
  {
    id: "c8",
    title: "الكيمياء – غير العضوية",
    subjectId: "chemistry",
    teacherId: "t3",
    description: "المعادن والمركبات غير العضوية",
    thumbnail: "https://images.unsplash.com/photo-1628863353691-0071c8c1874c?w=400&q=80",
    lectureCount: 10,
    level: "الصف الأول",
    isVisible: false,
    progress: 0,
  },
];

export const LECTURES: Lecture[] = [
  {
    id: "l1",
    title: "مقدمة في المجموعات",
    courseId: "c1",
    order: 1,
    completed: true,
    videos: [
      { id: "v1", title: "ما هي المجموعات؟", youtubeId: "dQw4w9WgXcQ", duration: "12:30", order: 1 },
      { id: "v2", title: "العمليات على المجموعات", youtubeId: "dQw4w9WgXcQ", duration: "18:45", order: 2 },
    ],
  },
  {
    id: "l2",
    title: "المعادلات من الدرجة الأولى",
    courseId: "c1",
    order: 2,
    completed: true,
    videos: [
      { id: "v3", title: "حل المعادلات", youtubeId: "dQw4w9WgXcQ", duration: "15:20", order: 1 },
      { id: "v4", title: "تطبيقات عملية", youtubeId: "dQw4w9WgXcQ", duration: "22:10", order: 2 },
    ],
  },
  {
    id: "l3",
    title: "المتراجحات",
    courseId: "c1",
    order: 3,
    completed: false,
    videos: [
      { id: "v5", title: "مفهوم المتراجحة", youtubeId: "dQw4w9WgXcQ", duration: "10:05", order: 1 },
      { id: "v6", title: "حل المتراجحات", youtubeId: "dQw4w9WgXcQ", duration: "20:30", order: 2 },
      { id: "v7", title: "مسائل وتطبيقات", youtubeId: "dQw4w9WgXcQ", duration: "25:00", order: 3 },
    ],
  },
  {
    id: "l4",
    title: "الدوال وأنواعها",
    courseId: "c1",
    order: 4,
    completed: false,
    videos: [
      { id: "v8", title: "تعريف الدالة", youtubeId: "dQw4w9WgXcQ", duration: "14:20", order: 1 },
      { id: "v9", title: "أنواع الدوال", youtubeId: "dQw4w9WgXcQ", duration: "19:45", order: 2 },
    ],
  },
  {
    id: "l5",
    title: "الهندسة الإحداثية",
    courseId: "c1",
    order: 5,
    completed: false,
    videos: [
      { id: "v10", title: "المحاور الإحداثية", youtubeId: "dQw4w9WgXcQ", duration: "11:30", order: 1 },
    ],
  },
];
